import json
import os

locales = {
    'en': {
        "Navigation": {
            "dashboard": "Dashboard",
            "reports": "My Reports",
            "chat": "AI Health Chat",
            "medications": "Medications",
            "insurance": "Insurance"
        },
        "Auth": {
            "signIn": "Sign In",
            "signUp": "Start for Free"
        },
        "Landing": {
            "badgeText": "Built for Indian Patients · Powered by AI",
            "heroTitle1": "Your Medical Reports,",
            "heroTitle2": "Explained Simply.",
            "heroSubtitle": "Upload lab reports, track medications, and navigate PM-JAY insurance schemes — all in plain language you can actually understand.",
            "btnStart": "Start for Free",
            "btnHowItWorks": "See How It Works",
            "sectionGapsTitle": "The 3 Healthcare Gaps We Solve",
            "sectionGapsSubtitle": "Common problems every Indian patient faces — and how we fix them.",
            "gap1Title": "Jargon Barriers",
            "gap1Desc": "Lab reports filled with medical terms your doctor never has time to explain clearly.",
            "gap2Title": "Missed Medications",
            "gap2Desc": "Critical doses forgotten with no smart reminders to keep adherence on track.",
            "gap3Title": "Insurance Chaos",
            "gap3Desc": "PM-JAY and state schemes that nobody can navigate without expert guidance.",
            "sectionStepsTitle": "How It Works",
            "sectionStepsSubtitle": "Three simple steps to take absolute control of your health journey.",
            "step1Title": "Upload Your Report",
            "step1Desc": "Snap a photo or upload a PDF. Any lab report, X-ray, or discharge summary works.",
            "step2Title": "AI Analyzes It",
            "step2Desc": "Our AI reads the medical jargon and translates every finding into simple language.",
            "step3Title": "Understand & Act",
            "step3Desc": "Get clear summaries, questions to ask your doctor, and insurance scheme guidance.",
            "sectionFeaturesTitle": "Everything you need in one place",
            "sectionFeaturesSubtitle": "A comprehensive suite of tools designed specifically for the modern Indian healthcare experience.",
            "feature1Title": "Report Analysis",
            "feature1Desc": "AI explains your lab results in plain language you can actually understand.",
            "feature2Title": "AI Health Chat",
            "feature2Desc": "Ask anything about your health history. Get context-aware answers.",
            "feature3Title": "Medication Tracker",
            "feature3Desc": "Never miss a dose. Smart schedules with adherence logging.",
            "feature4Title": "Insurance Navigator",
            "feature4Desc": "Find PM-JAY schemes that cover your specific procedure effortlessly.",
            "feature5Title": "Health Timeline",
            "feature5Desc": "Your complete medical journey visualized in a single chronological view.",
            "feature6Title": "Doctor Dashboard",
            "feature6Desc": "Doctors monitor patient adherence and flag at-risk patients instantly."
        },
        "Dashboard": {
            "greeting": "Hello",
            "welcomeText": "Here's what's happening with your health today.",
            "quickActions": "Quick Actions",
            "uploadReportBtn": "Upload Report",
            "addMedicationBtn": "Add Medication",
            "chatWithAIBtn": "Chat with AI",
            "recentReports": "Recent Reports",
            "noReports": "No reports uploaded yet.",
            "uploadYourFirstReport": "Upload your first medical report to get started."
        },
        "Settings": {
            "title": "Account Settings",
            "subtitle": "Manage your security, preferences, and notifications",
            "security": "Security & Password",
            "changePassword": "Change Password",
            "currentPassword": "Current Password",
            "newPassword": "New Password",
            "confirmPassword": "Confirm Password",
            "deleteAccount": "Delete Account",
            "deleteWarning": "Once you delete your account, there is no going back. Please be certain.",
            "notifications": "Notifications & Alarms",
            "pushAlarms": "Medication Push Alarms",
            "pushDesc": "Receive desktop and mobile notifications when it's time to take your medication.",
            "enableAlarms": "Enable Push Alarms",
            "testAlarm": "Test Alarm"
        },
        "Profile": {
            "title": "Medical Profile",
            "subtitle": "Your central health passport. Keep this updated for accurate AI analysis.",
            "abhaId": "ABHA ID (Health ID)",
            "demographics": "Demographics",
            "age": "Age",
            "gender": "Gender",
            "bloodGroup": "Blood Group",
            "weight": "Weight (kg)",
            "height": "Height (cm)",
            "medicalHistory": "Medical History",
            "conditions": "Pre-existing Conditions",
            "allergies": "Known Allergies",
            "emergency": "Emergency Contact",
            "contactName": "Contact Name",
            "contactPhone": "Contact Phone",
            "saveChanges": "Save Changes"
        }
    },
    'hi': {
        "Navigation": {
            "dashboard": "डैशबोर्ड",
            "reports": "मेरी रिपोर्ट",
            "chat": "AI स्वास्थ्य चैट",
            "medications": "दवाइयाँ",
            "insurance": "बीमा"
        },
        "Auth": {
            "signIn": "साइन इन करें",
            "signUp": "मुफ़्त शुरू करें"
        },
        "Landing": {
            "badgeText": "भारतीय मरीजों के लिए निर्मित · AI द्वारा संचालित",
            "heroTitle1": "आपकी मेडिकल रिपोर्ट,",
            "heroTitle2": "सरल भाषा में समझाई गई।",
            "heroSubtitle": "लैब रिपोर्ट अपलोड करें, दवाइयाँ ट्रैक करें और PM-JAY बीमा योजनाओं को आसानी से समझें — सब कुछ आपकी अपनी भाषा में।",
            "btnStart": "मुफ़्त शुरू करें",
            "btnHowItWorks": "यह कैसे काम करता है",
            "sectionGapsTitle": "3 स्वास्थ्य संबंधी कमियाँ जिन्हें हम हल करते हैं",
            "sectionGapsSubtitle": "हर भारतीय मरीज के सामने आने वाली आम समस्याएँ — और हम उन्हें कैसे ठीक करते हैं।",
            "gap1Title": "कठिन शब्दावली",
            "gap1Desc": "मेडिकल शब्दों से भरी लैब रिपोर्ट जिसे समझाने का समय आपके डॉक्टर के पास कभी नहीं होता।",
            "gap2Title": "दवाइयों का छूटना",
            "gap2Desc": "स्मार्ट रिमाइंडर के बिना महत्वपूर्ण खुराकों का भूल जाना।",
            "gap3Title": "बीमा की उलझन",
            "gap3Desc": "PM-JAY और राज्य की योजनाएँ जिन्हें विशेषज्ञ मार्गदर्शन के बिना कोई नहीं समझ सकता।",
            "sectionStepsTitle": "यह कैसे काम करता है",
            "sectionStepsSubtitle": "अपनी स्वास्थ्य यात्रा को पूरी तरह से नियंत्रित करने के 3 आसान चरण।",
            "step1Title": "अपनी रिपोर्ट अपलोड करें",
            "step1Desc": "फोटो खींचें या PDF अपलोड करें। कोई भी लैब रिपोर्ट, एक्स-रे या डिस्चार्ज समरी काम करेगी।",
            "step2Title": "AI इसका विश्लेषण करता है",
            "step2Desc": "हमारा AI मेडिकल शब्दों को पढ़ता है और हर जानकारी का सरल भाषा में अनुवाद करता है।",
            "step3Title": "समझें और कार्य करें",
            "step3Desc": "स्पष्ट सारांश, अपने डॉक्टर से पूछने के लिए प्रश्न और बीमा योजना मार्गदर्शन प्राप्त करें।",
            "sectionFeaturesTitle": "आपको जो भी चाहिए वह सब एक ही स्थान पर",
            "sectionFeaturesSubtitle": "आधुनिक भारतीय स्वास्थ्य सेवा अनुभव के लिए विशेष रूप से डिज़ाइन किए गए उपकरणों का एक व्यापक सूट।",
            "feature1Title": "रिपोर्ट विश्लेषण",
            "feature1Desc": "AI आपके लैब परिणामों को सरल भाषा में समझाता है जिसे आप वास्तव में समझ सकते हैं।",
            "feature2Title": "AI स्वास्थ्य चैट",
            "feature2Desc": "अपने स्वास्थ्य इतिहास के बारे में कुछ भी पूछें। प्रासंगिक उत्तर प्राप्त करें।",
            "feature3Title": "दवाइयों का ट्रैकर",
            "feature3Desc": "कभी भी कोई खुराक न भूलें। स्मार्ट शेड्यूल और लॉगिंग के साथ।",
            "feature4Title": "बीमा नेविगेटर",
            "feature4Desc": "PM-JAY योजनाएँ खोजें जो आपकी विशिष्ट प्रक्रिया को आसानी से कवर करती हैं।",
            "feature5Title": "स्वास्थ्य टाइमलाइन",
            "feature5Desc": "आपकी संपूर्ण चिकित्सा यात्रा एक ही कालानुक्रमिक दृश्य में देखी जा सकती है।",
            "feature6Title": "डॉक्टर डैशबोर्ड",
            "feature6Desc": "डॉक्टर मरीजों की निगरानी करते हैं और जोखिम वाले मरीजों को तुरंत चिह्नित करते हैं।"
        },
        "Dashboard": {
            "greeting": "नमस्ते",
            "welcomeText": "आज आपके स्वास्थ्य के साथ क्या हो रहा है, यह यहाँ दिया गया है।",
            "quickActions": "त्वरित क्रियाएँ",
            "uploadReportBtn": "रिपोर्ट अपलोड करें",
            "addMedicationBtn": "दवा जोड़ें",
            "chatWithAIBtn": "AI के साथ चैट करें",
            "recentReports": "हाल की रिपोर्ट",
            "noReports": "अभी तक कोई रिपोर्ट अपलोड नहीं की गई है।",
            "uploadYourFirstReport": "आरंभ करने के लिए अपनी पहली मेडिकल रिपोर्ट अपलोड करें।"
        }
    },
    'mr': {
        "Navigation": {
            "dashboard": "डॅशबोर्ड",
            "reports": "माझे अहवाल",
            "chat": "AI आरोग्य गप्पा",
            "medications": "औषधे",
            "insurance": "विमा"
        },
        "Auth": {
            "signIn": "लॉग इन करा",
            "signUp": "मोफत सुरू करा"
        },
        "Landing": {
            "badgeText": "भारतीय रुग्णांसाठी निर्मित · AI द्वारा समर्थित",
            "heroTitle1": "तुमचे वैद्यकीय अहवाल,",
            "heroTitle2": "सोप्या भाषेत स्पष्ट केलेले.",
            "heroSubtitle": "लॅब रिपोर्ट्स अपलोड करा, औषधांचा मागोवा घ्या आणि PM-JAY विमा योजना सोप्या भाषेत समजून घ्या.",
            "btnStart": "मोफत सुरू करा",
            "btnHowItWorks": "हे कसे कार्य करते",
            "sectionGapsTitle": "आम्ही सोडवतो ते ३ आरोग्यसेवा प्रश्न",
            "sectionGapsSubtitle": "प्रत्येक भारतीय रुग्णाला भेडसावणाऱ्या सामान्य समस्या — आणि आम्ही त्या कशा सोडवतो.",
            "gap1Title": "कठीण वैद्यकीय शब्द",
            "gap1Desc": "वैद्यकीय शब्दांनी भरलेले लॅब रिपोर्ट्स जे समजून सांगण्यासाठी तुमच्या डॉक्टरांना कधीही वेळ नसतो.",
            "gap2Title": "विसरलेली औषधे",
            "gap2Desc": "स्मार्ट रिमाइंडर्स नसल्यामुळे महत्त्वाची औषधे विसरणे.",
            "gap3Title": "विम्याचा गोंधळ",
            "gap3Desc": "PM-JAY आणि राज्य योजना ज्या तज्ञांच्या मार्गदर्शनाशिवाय कोणीही समजू शकत नाही.",
            "sectionStepsTitle": "हे कसे कार्य करते",
            "sectionStepsSubtitle": "तुमच्या आरोग्यावर पूर्ण नियंत्रण मिळवण्यासाठी तीन सोप्या पायऱ्या.",
            "step1Title": "तुमचा अहवाल अपलोड करा",
            "step1Desc": "फोटो काढा किंवा PDF अपलोड करा. कोणताही लॅब रिपोर्ट, एक्स-रे किंवा डिस्चार्ज समरी चालेल.",
            "step2Title": "AI त्याचे विश्लेषण करते",
            "step2Desc": "आमचे AI वैद्यकीय शब्द वाचते आणि प्रत्येक निष्कर्षाचे साध्या भाषेत भाषांतर करते.",
            "step3Title": "समजून घ्या आणि कार्य करा",
            "step3Desc": "स्पष्ट सारांश मिळवा, डॉक्टरांना विचारण्यासाठी प्रश्न आणि विमा योजनेबद्दल मार्गदर्शन मिळवा.",
            "sectionFeaturesTitle": "तुम्हाला हवे असलेले सर्व काही एकाच ठिकाणी",
            "sectionFeaturesSubtitle": "आधुनिक भारतीय आरोग्यसेवा अनुभवासाठी विशेषतः डिझाइन केलेले एक व्यापक टूल संच.",
            "feature1Title": "अहवाल विश्लेषण",
            "feature1Desc": "AI तुमचे लॅब निकाल साध्या भाषेत स्पष्ट करते जे तुम्हाला खरोखर समजू शकतात.",
            "feature2Title": "AI आरोग्य गप्पा",
            "feature2Desc": "तुमच्या आरोग्याच्या इतिहासाबद्दल काहीही विचारा. संदर्भ-अचूक उत्तरे मिळवा.",
            "feature3Title": "औषध ट्रॅकर",
            "feature3Desc": "कधीही औषध चुकवू नका. स्मार्ट वेळापत्रके.",
            "feature4Title": "विमा नेव्हिगेटर",
            "feature4Desc": "तुमच्या विशिष्ट प्रक्रियेला कव्हर करणाऱ्या PM-JAY योजना सहज शोधा.",
            "feature5Title": "आरोग्य टाइमलाइन",
            "feature5Desc": "तुमचा संपूर्ण वैद्यकीय प्रवास एकाच कालक्रमानुसार पाहता येतो.",
            "feature6Title": "डॉक्टर डॅशबोर्ड",
            "feature6Desc": "डॉक्टर रुग्णांच्या औषधोपचारांवर लक्ष ठेवतात आणि जोखमीच्या रुग्णांना त्वरित सूचित करतात."
        },
        "Dashboard": {
            "greeting": "नमस्कार",
            "welcomeText": "आज तुमच्या आरोग्याबाबत काय घडत आहे ते येथे आहे.",
            "quickActions": "त्वरित क्रिया",
            "uploadReportBtn": "अहवाल अपलोड करा",
            "addMedicationBtn": "औषध जोडा",
            "chatWithAIBtn": "AI सोबत गप्पा मारा",
            "recentReports": "अलीकडील अहवाल",
            "noReports": "अद्याप कोणतेही अहवाल अपलोड केलेले नाहीत.",
            "uploadYourFirstReport": "सुरू करण्यासाठी तुमचा पहिला वैद्यकीय अहवाल अपलोड करा."
        }
    },
    'ur': {
        "Navigation": {
            "dashboard": "ڈیش بورڈ",
            "reports": "میری رپورٹس",
            "chat": "AI ہیلتھ چیٹ",
            "medications": "ادویات",
            "insurance": "انشورنس"
        },
        "Auth": {
            "signIn": "سائن ان",
            "signUp": "مفت شروع کریں"
        },
        "Landing": {
            "badgeText": "ہندوستانی مریضوں کے لیے تیار کردہ · AI کے ذریعے تقویت یافتہ",
            "heroTitle1": "آپ کی میڈیکل رپورٹس،",
            "heroTitle2": "آسان الفاظ میں سمجھائی گئیں۔",
            "heroSubtitle": "لیب رپورٹس اپ لوڈ کریں، ادویات کو ٹریک کریں اور PM-JAY انشورنس اسکیموں کو آسانی سے سمجھیں۔",
            "btnStart": "مفت شروع کریں",
            "btnHowItWorks": "یہ کیسے کام کرتا ہے",
            "sectionGapsTitle": "3 صحت کے مسائل جنہیں ہم حل کرتے ہیں",
            "sectionGapsSubtitle": "عام مسائل جن کا سامنا ہر ہندوستانی مریض کو ہوتا ہے۔",
            "gap1Title": "مشکل الفاظ",
            "gap1Desc": "طبی اصطلاحات سے بھری لیب رپورٹس جنہیں سمجھانے کا وقت آپ کے ڈاکٹر کے پاس کبھی نہیں ہوتا۔",
            "gap2Title": "بھولی ہوئی ادویات",
            "gap2Desc": "سمارٹ ریمائنڈرز کے بغیر اہم ادویات کا بھول جانا۔",
            "gap3Title": "انشورنس کی الجھن",
            "gap3Desc": "ایسی اسکیمیں جنہیں ماہرین کی رہنمائی کے بغیر کوئی نہیں سمجھ سکتا۔",
            "sectionStepsTitle": "یہ کیسے کام کرتا ہے",
            "sectionStepsSubtitle": "اپنی صحت کے سفر کو کنٹرول کرنے کے 3 آسان اقدامات۔",
            "step1Title": "اپنی رپورٹ اپ لوڈ کریں",
            "step1Desc": "تصویر لیں یا پی ڈی ایف اپ لوڈ کریں۔",
            "step2Title": "AI اس کا تجزیہ کرتا ہے",
            "step2Desc": "ہمارا AI طبی اصطلاحات کو پڑھتا ہے اور انہیں آسان زبان میں ترجمہ کرتا ہے۔",
            "step3Title": "سمجھیں اور عمل کریں",
            "step3Desc": "واضح خلاصے اور اپنے ڈاکٹر سے پوچھنے کے لیے سوالات حاصل کریں۔",
            "sectionFeaturesTitle": "آپ کی ضرورت کی ہر چیز ایک جگہ",
            "sectionFeaturesSubtitle": "ہندوستانی صحت کی دیکھ بھال کے تجربے کے لئے ایک جامع ٹول۔",
            "feature1Title": "رپورٹ کا تجزیہ",
            "feature1Desc": "AI آپ کے لیب کے نتائج کو آسان زبان میں سمجھاتا ہے۔",
            "feature2Title": "AI ہیلتھ چیٹ",
            "feature2Desc": "اپنی صحت کی تاریخ کے بارے میں کچھ بھی پوچھیں۔",
            "feature3Title": "میڈیکیشن ٹریکر",
            "feature3Desc": "کبھی بھی کوئی دوا نہ بھولیں۔ سمارٹ نظام الاوقات۔",
            "feature4Title": "انشورنس نیویگیٹر",
            "feature4Desc": "PM-JAY اسکیمیں آسانی سے تلاش کریں۔",
            "feature5Title": "ہیلتھ ٹائم لائن",
            "feature5Desc": "آپ کا مکمل طبی سفر ایک ہی نظارے میں دیکھا جاسکتا ہے۔",
            "feature6Title": "ڈاکٹر ڈیش بورڈ",
            "feature6Desc": "ڈاکٹر مریضوں کی نگرانی کرتے ہیں اور خطرے والے مریضوں کی نشاندہی کرتے ہیں۔"
        },
        "Dashboard": {
            "greeting": "ہیلو",
            "welcomeText": "آج آپ کی صحت کے ساتھ کیا ہو رہا ہے، یہ یہاں ہے۔",
            "quickActions": "فوری اقدامات",
            "uploadReportBtn": "رپورٹ اپ لوڈ کریں",
            "addMedicationBtn": "دوا شامل کریں",
            "chatWithAIBtn": "AI کے ساتھ چیٹ کریں",
            "recentReports": "حالیہ رپورٹس",
            "noReports": "ابھی تک کوئی رپورٹ اپ لوڈ نہیں کی گئی ہے۔",
            "uploadYourFirstReport": "شروع کرنے کے لیے اپنی پہلی میڈیکل رپورٹ اپ لوڈ کریں۔"
        }
    },
    'te': {
        "Navigation": {
            "dashboard": "డాష్‌బోర్డ్",
            "reports": "నా నివేదికలు",
            "chat": "AI హెల్త్ చాట్",
            "medications": "మందులు",
            "insurance": "భీమా"
        },
        "Auth": {
            "signIn": "సైన్ ఇన్ చేయండి",
            "signUp": "ఉచితంగా ప్రారంభించండి"
        },
        "Landing": {
            "badgeText": "భారతీయ రోగుల కోసం నిర్మించబడింది · AI ద్వారా ఆధారితం",
            "heroTitle1": "మీ వైద్య నివేదికలు,",
            "heroTitle2": "సులభంగా వివరించబడ్డాయి.",
            "heroSubtitle": "ల్యాబ్ నివేదికలను అప్‌లోడ్ చేయండి, మందులను ట్రాక్ చేయండి మరియు PM-JAY బీమా పథకాలను సులభంగా నావిగేట్ చేయండి.",
            "btnStart": "ఉచితంగా ప్రారంభించండి",
            "btnHowItWorks": "ఇది ఎలా పనిచేస్తుందో చూడండి",
            "sectionGapsTitle": "మేము పరిష్కరించే 3 ఆరోగ్య సంరక్షణ అంతరాలు",
            "sectionGapsSubtitle": "ప్రతి భారతీయ రోగి ఎదుర్కొనే సాధారణ సమస్యలు — మరియు మేము వాటిని ఎలా పరిష్కరిస్తాము.",
            "gap1Title": "వైద్య పదజాలం",
            "gap1Desc": "మీ వైద్యుడు ఎప్పుడూ స్పష్టంగా వివరించడానికి సమయం లేని వైద్య పదాలతో నిండిన ల్యాబ్ నివేదికలు.",
            "gap2Title": "మరచిపోయిన మందులు",
            "gap2Desc": "స్మార్ట్ రిమైండర్‌లు లేకుండా ముఖ్యమైన మందులు తీసుకోవడం మరచిపోవడం.",
            "gap3Title": "భీమా గందరగోళం",
            "gap3Desc": "నిపుణుల మార్గదర్శకత్వం లేకుండా ఎవరూ నావిగేట్ చేయలేని PM-JAY మరియు రాష్ట్ర పథకాలు.",
            "sectionStepsTitle": "ఇది ఎలా పనిచేస్తుంది",
            "sectionStepsSubtitle": "మీ ఆరోగ్య ప్రయాణంపై పూర్తి నియంత్రణ సాధించడానికి మూడు సులభమైన దశలు.",
            "step1Title": "మీ నివేదికను అప్‌లోడ్ చేయండి",
            "step1Desc": "ఫోటో తీయండి లేదా PDFని అప్‌లోడ్ చేయండి. ఏదైనా ల్యాబ్ రిపోర్ట్ లేదా ఎక్స్-రే పనిచేస్తుంది.",
            "step2Title": "AI విశ్లేషిస్తుంది",
            "step2Desc": "మా AI వైద్య పదజాలాన్ని చదివి ప్రతి ఫలితాన్ని సాధారణ భాషలోకి అనువదిస్తుంది.",
            "step3Title": "అర్థం చేసుకోండి మరియు పని చేయండి",
            "step3Desc": "స్పష్టమైన సారాంశాలు మరియు బీమా పథకం మార్గదర్శకత్వం పొందండి.",
            "sectionFeaturesTitle": "మీకు కావలసినవన్నీ ఒకే చోట",
            "sectionFeaturesSubtitle": "ఆధునిక భారతీయ ఆరోగ్య సంరక్షణ అనుభవం కోసం ప్రత్యేకంగా రూపొందించబడిన సాధనాల సమగ్ర సూట్.",
            "feature1Title": "నివేదిక విశ్లేషణ",
            "feature1Desc": "AI మీ ల్యాబ్ ఫలితాలను మీరు అర్థం చేసుకోగల సాధారణ భాషలో వివరిస్తుంది.",
            "feature2Title": "AI హెల్త్ చాట్",
            "feature2Desc": "మీ ఆరోగ్య చరిత్ర గురించి ఏదైనా అడగండి.",
            "feature3Title": "మెడికేషన్ ట్రాకర్",
            "feature3Desc": "ఎప్పుడూ మందులు వేసుకోవడం మరచిపోకండి. స్మార్ట్ షెడ్యూల్స్.",
            "feature4Title": "ఇన్సూరెన్స్ నావిగేటర్",
            "feature4Desc": "మీ నిర్దిష్ట విధానాన్ని కవర్ చేసే PM-JAY పథకాలను సులభంగా కనుగొనండి.",
            "feature5Title": "హెల్త్ టైమ్‌లైన్",
            "feature5Desc": "మీ పూర్తి వైద్య ప్రయాణం ఒకే కాలానుక్రమ వీక్షణలో దൃശ్యమానం చేయబడింది.",
            "feature6Title": "డాక్టర్ డాష్‌బోర్డ్",
            "feature6Desc": "వైద్యులు రోగుల ఔషధాలను పర్యవేక్షిస్తారు మరియు ప్రమాదంలో ఉన్న రోగులను గుర్తిస్తారు."
        },
        "Dashboard": {
            "greeting": "హలో",
            "welcomeText": "ఈరోజు మీ ఆరోగ్యంతో ఏమి జరుగుతుందో ఇక్కడ ఉంది.",
            "quickActions": "శీఘ్ర చర్యలు",
            "uploadReportBtn": "నివేదికను అప్‌లోడ్ చేయండి",
            "addMedicationBtn": "మందును జోడించండి",
            "chatWithAIBtn": "AIతో చాట్ చేయండి",
            "recentReports": "ఇటీవలి నివేదికలు",
            "noReports": "ఇంకా ఎలాంటి నివేదికలు అప్‌లోడ్ చేయబడలేదు.",
            "uploadYourFirstReport": "ప్రారంభించడానికి మీ మొదటి వైద్య నివేదికను అప్‌లోడ్ చేయండి."
        }
    },
    'bn': {
        "Navigation": {
            "dashboard": "ড্যাশবোর্ড",
            "reports": "আমার রিপোর্ট",
            "chat": "AI হেলথ চ্যাট",
            "medications": "ওষুধ",
            "insurance": "বীমা"
        },
        "Auth": {
            "signIn": "সাইন ইন করুন",
            "signUp": "বিনামূল্যে শুরু করুন"
        },
        "Landing": {
            "badgeText": "ভারতীয় রোগীদের জন্য নির্মিত · AI দ্বারা চালিত",
            "heroTitle1": "আপনার মেডিকেল রিপোর্ট,",
            "heroTitle2": "সহজভাবে ব্যাখ্যা করা হয়েছে।",
            "heroSubtitle": "ল্যাব রিপোর্ট আপলোড করুন, ওষুধের ট্র্যাক রাখুন এবং PM-JAY বীমা স্কিমগুলি সহজেই নেভিগেট করুন।",
            "btnStart": "বিনামূল্যে শুরু করুন",
            "btnHowItWorks": "এটি কীভাবে কাজ করে",
            "sectionGapsTitle": "৩টি স্বাস্থ্যসেবা ফাঁক যা আমরা সমাধান করি",
            "sectionGapsSubtitle": "প্রতিটি ভারতীয় রোগীর মুখোমুখি হওয়া সাধারণ সমস্যা — এবং আমরা কীভাবে সেগুলি ঠিক করি।",
            "gap1Title": "কঠিন শব্দভাণ্ডার",
            "gap1Desc": "মেডিকেল শব্দে ভরা ল্যাব রিপোর্ট যা আপনার ডাক্তারের কাছে কখনই পরিষ্কারভাবে ব্যাখ্যা করার সময় থাকে না।",
            "gap2Title": "ভুলে যাওয়া ওষুধ",
            "gap2Desc": "স্মার্ট রিমাইন্ডার ছাড়াই প্রয়োজনীয় ডোজ ভুলে যাওয়া।",
            "gap3Title": "বীমা বিশৃঙ্খলা",
            "gap3Desc": "PM-JAY এবং রাষ্ট্রীয় স্কিম যা বিশেষজ্ঞের নির্দেশিকা ছাড়া কেউ বুঝতে পারে না।",
            "sectionStepsTitle": "এটি কীভাবে কাজ করে",
            "sectionStepsSubtitle": "আপনার স্বাস্থ্য যাত্রার সম্পূর্ণ নিয়ন্ত্রণ নেওয়ার তিনটি সহজ পদক্ষেপ।",
            "step1Title": "আপনার রিপোর্ট আপলোড করুন",
            "step1Desc": "একটি ছবি তুলুন বা পিডিএফ আপলোড করুন। যেকোনো ল্যাব রিপোর্ট বা এক্স-রে কাজ করবে।",
            "step2Title": "AI এটি বিশ্লেষণ করে",
            "step2Desc": "আমাদের AI মেডিকেল শব্দগুলি পড়ে এবং প্রতিটি ফলাফলকে সহজ ভাষায় অনুবাদ করে।",
            "step3Title": "বুঝুন এবং কাজ করুন",
            "step3Desc": "স্পষ্ট সারসংক্ষেপ, আপনার ডাক্তারকে জিজ্ঞাসা করার প্রশ্ন এবং বীমা স্কিমের নির্দেশিকা পান।",
            "sectionFeaturesTitle": "আপনার প্রয়োজনীয় সবকিছু এক জায়গায়",
            "sectionFeaturesSubtitle": "আধুনিক ভারতীয় স্বাস্থ্যসেবা অভিজ্ঞতার জন্য বিশেষভাবে ডিজাইন করা একটি বিস্তৃত সরঞ্জাম স্যুট।",
            "feature1Title": "রিপোর্ট বিশ্লেষণ",
            "feature1Desc": "AI আপনার ল্যাবের ফলাফলগুলি সহজ ভাষায় ব্যাখ্যা করে যা আপনি বুঝতে পারেন।",
            "feature2Title": "AI হেলথ চ্যাট",
            "feature2Desc": "আপনার স্বাস্থ্যের ইতিহাস সম্পর্কে যেকোনো কিছু জিজ্ঞাসা করুন।",
            "feature3Title": "ওষুধ ট্র্যাকার",
            "feature3Desc": "কখনই একটি ডোজ মিস করবেন না। স্মার্ট সময়সূচী।",
            "feature4Title": "বীমা নেভিগেটর",
            "feature4Desc": "PM-JAY স্কিমগুলি সন্ধান করুন যা অনায়াসে আপনার নির্দিষ্ট প্রক্রিয়াটি কভার করে।",
            "feature5Title": "হেলথ টাইমলাইন",
            "feature5Desc": "আপনার সম্পূর্ণ মেডিকেল যাত্রা একটি কালানুক্রমিক দৃশ্যে দেখা যায়।",
            "feature6Title": "ডাক্তার ড্যাশবোর্ড",
            "feature6Desc": "ডাক্তাররা রোগীদের ওষুধের উপর নজর রাখেন এবং ঝুঁকিপূর্ণ রোগীদের চিহ্নিত করেন।"
        },
        "Dashboard": {
            "greeting": "নমস্কার",
            "welcomeText": "আজ আপনার স্বাস্থ্যের সাথে কী ঘটছে তা এখানে রয়েছে।",
            "quickActions": "দ্রুত পদক্ষেপ",
            "uploadReportBtn": "রিপোর্ট আপলোড করুন",
            "addMedicationBtn": "ওষুধ যোগ করুন",
            "chatWithAIBtn": "AI এর সাথে চ্যাট করুন",
            "recentReports": "সাম্প্রতিক রিপোর্ট",
            "noReports": "এখনও কোনও রিপোর্ট আপলোড করা হয়নি।",
            "uploadYourFirstReport": "শুরু করতে আপনার প্রথম মেডিকেল রিপোর্ট আপলোড করুন।"
        }
    },
    'ta': {
        "Navigation": {
            "dashboard": "டாஷ்போர்டு",
            "reports": "என் அறிக்கைகள்",
            "chat": "AI சுகாதார அரட்டை",
            "medications": "மருந்துகள்",
            "insurance": "காப்பீடு"
        },
        "Auth": {
            "signIn": "உள்நுழைக",
            "signUp": "இலவசமாக தொடங்குங்கள்"
        },
        "Landing": {
            "badgeText": "இந்திய நோயாளிகளுக்காக உருவாக்கப்பட்டது · AI ஆல் இயக்கப்படுகிறது",
            "heroTitle1": "உங்கள் மருத்துவ அறிக்கைகள்,",
            "heroTitle2": "எளிமையாக விளக்கப்பட்டுள்ளன.",
            "heroSubtitle": "ஆய்வக அறிக்கைகளை பதிவேற்றவும், மருந்துகளை கண்காணிக்கவும் மற்றும் PM-JAY காப்பீட்டு திட்டங்களை எளிதாக புரிந்துகொள்ளவும்.",
            "btnStart": "இலவசமாக தொடங்குங்கள்",
            "btnHowItWorks": "எப்படி வேலை செய்கிறது",
            "sectionGapsTitle": "நாம் தீர்க்கும் 3 சுகாதார குறைபாடுகள்",
            "sectionGapsSubtitle": "ஒவ்வொரு இந்திய நோயாளியும் எதிர்கொள்ளும் பொதுவான பிரச்சினைகள் — அவற்றை நாம் எப்படி சரிசெய்கிறோம்.",
            "gap1Title": "மருத்துவ சொற்கள்",
            "gap1Desc": "உங்கள் மருத்துவருக்கு விளக்க நேரமில்லாத கடினமான மருத்துவ சொற்கள் நிறைந்த ஆய்வக அறிக்கைகள்.",
            "gap2Title": "மறக்கப்பட்ட மருந்துகள்",
            "gap2Desc": "ஸ்மார்ட் நினைவூட்டல்கள் இல்லாமல் முக்கியமான மருந்துகளை எடுக்க மறப்பது.",
            "gap3Title": "காப்பீட்டு குழப்பம்",
            "gap3Desc": "நிபுணர் வழிகாட்டுதல் இல்லாமல் யாரும் எளிதில் புரிந்துகொள்ள முடியாத PM-JAY மற்றும் மாநில திட்டங்கள்.",
            "sectionStepsTitle": "இது எப்படி வேலை செய்கிறது",
            "sectionStepsSubtitle": "உங்கள் சுகாதார பயணத்தின் மீது முழு கட்டுப்பாடு பெற மூன்று எளிய படிகள்.",
            "step1Title": "உங்கள் அறிக்கையை பதிவேற்றவும்",
            "step1Desc": "ஒரு புகைப்படத்தை எடுக்கவும் அல்லது PDF ஐ பதிவேற்றவும்.",
            "step2Title": "AI பகுப்பாய்வு செய்கிறது",
            "step2Desc": "நமது AI மருத்துவ சொற்களைப் படித்து ஒவ்வொரு முடிவையும் எளிய மொழியில் மொழிபெயர்க்கிறது.",
            "step3Title": "புரிந்துகொண்டு செயல்படுங்கள்",
            "step3Desc": "தெளிவான சுருக்கங்கள் மற்றும் காப்பீட்டு திட்ட வழிகாட்டுதல்களைப் பெறுங்கள்.",
            "sectionFeaturesTitle": "உங்களுக்கு தேவையான அனைத்தும் ஒரே இடத்தில்",
            "sectionFeaturesSubtitle": "நவீன இந்திய சுகாதார அனுபவத்திற்காக பிரத்யேகமாக வடிவமைக்கப்பட்ட கருவிகள்.",
            "feature1Title": "அறிக்கை பகுப்பாய்வு",
            "feature1Desc": "AI உங்கள் ஆய்வக முடிவுகளை நீங்கள் புரிந்துகொள்ளக்கூடிய எளிய மொழியில் விளக்குகிறது.",
            "feature2Title": "AI சுகாதார அரட்டை",
            "feature2Desc": "உங்கள் சுகாதார வரலாறு பற்றி எதையும் கேளுங்கள்.",
            "feature3Title": "மருந்து கண்காணிப்பாளர்",
            "feature3Desc": "ஒருபோதும் ஒரு அளவை தவறவிடாதீர்கள். ஸ்மார்ட் அட்டவணைகள்.",
            "feature4Title": "காப்பீட்டு வழிகாட்டி",
            "feature4Desc": "உங்கள் குறிப்பிட்ட சிகிச்சைக்கான PM-JAY திட்டங்களை எளிதாகக் கண்டறியவும்.",
            "feature5Title": "சுகாதார காலவரிசை",
            "feature5Desc": "உங்கள் முழுமையான மருத்துவ பயணம் ஒரே காலவரிசை பார்வையில்.",
            "feature6Title": "மருத்துவர் டாஷ்போர்டு",
            "feature6Desc": "மருத்துவர்கள் நோயாளிகளைக் கண்காணித்து ஆபத்தில் உள்ள நோயாளிகளை உடனடியாக அடையாளம் காண்கின்றனர்."
        },
        "Dashboard": {
            "greeting": "வணக்கம்",
            "welcomeText": "இன்று உங்கள் உடல்நலத்தைப் பற்றி என்ன நடக்கிறது என்பது இங்கே.",
            "quickActions": "விரைவு செயல்கள்",
            "uploadReportBtn": "அறிக்கையை பதிவேற்றவும்",
            "addMedicationBtn": "மருந்தைச் சேர்க்கவும்",
            "chatWithAIBtn": "AI உடன் அரட்டையடிக்கவும்",
            "recentReports": "சமீபத்திய அறிக்கைகள்",
            "noReports": "இன்னும் அறிக்கைகள் பதிவேற்றப்படவில்லை.",
            "uploadYourFirstReport": "தொடங்க உங்கள் முதல் மருத்துவ அறிக்கையை பதிவேற்றவும்."
        }
    },
    'gu': {
        "Navigation": {
            "dashboard": "ડેશબોર્ડ",
            "reports": "મારા અહેવાલો",
            "chat": "AI હેલ્થ ચેટ",
            "medications": "દવાઓ",
            "insurance": "વીમો"
        },
        "Auth": {
            "signIn": "લૉગ ઇન કરો",
            "signUp": "મફતમાં શરૂ કરો"
        },
        "Landing": {
            "badgeText": "ભારતીય દર્દીઓ માટે બનાવેલ · AI દ્વારા સંચાલિત",
            "heroTitle1": "તમારા તબીબી અહેવાલો,",
            "heroTitle2": "સરળ શબ્દોમાં સમજાવ્યા છે.",
            "heroSubtitle": "લેબ રિપોર્ટ્સ અપલોડ કરો, દવાઓ ટ્રૅક કરો અને PM-JAY વીમા યોજનાઓ સરળતાથી સમજો.",
            "btnStart": "મફતમાં શરૂ કરો",
            "btnHowItWorks": "તે કેવી રીતે કાર્ય કરે છે",
            "sectionGapsTitle": "3 આરોગ્યસંભાળ સમસ્યાઓ જે અમે હલ કરીએ છીએ",
            "sectionGapsSubtitle": "દરેક ભારતીય દર્દી સામનો કરે છે તેવી સામાન્ય સમસ્યાઓ.",
            "gap1Title": "અઘરા તબીબી શબ્દો",
            "gap1Desc": "તબીબી શબ્દોથી ભરેલા લેબ રિપોર્ટ્સ જેને સમજાવવા માટે તમારા ડૉક્ટર પાસે ક્યારેય સમય નથી હોતો.",
            "gap2Title": "ભૂલી ગયેલી દવાઓ",
            "gap2Desc": "સ્માર્ટ રિમાઇન્ડર્સ વિના મહત્વપૂર્ણ દવાઓ લેવાનું ભૂલી જવું.",
            "gap3Title": "વીમાની મૂંઝવણ",
            "gap3Desc": "નિષ્ણાતના માર્ગદર્શન વિના કોઈ સમજી ન શકે તેવી PM-JAY યોજનાઓ.",
            "sectionStepsTitle": "તે કેવી રીતે કાર્ય કરે છે",
            "sectionStepsSubtitle": "તમારી આરોગ્ય યાત્રા પર સંપૂર્ણ નિયંત્રણ મેળવવા માટે ત્રણ સરળ પગલાં.",
            "step1Title": "તમારો રિપોર્ટ અપલોડ કરો",
            "step1Desc": "ફોટો લો અથવા PDF અપલોડ કરો.",
            "step2Title": "AI વિશ્લેષણ કરે છે",
            "step2Desc": "અમારું AI તબીબી શબ્દભંડોળ વાંચે છે અને સરળ ભાષામાં ભાષાંતર કરે છે.",
            "step3Title": "સમજો અને પગલાં લો",
            "step3Desc": "સ્પષ્ટ સારાંશ અને તમારા ડૉક્ટરને પૂછવા માટેના પ્રશ્નો મેળવો.",
            "sectionFeaturesTitle": "તમને જોઈતું બધું એક જ જગ્યાએ",
            "sectionFeaturesSubtitle": "આધુનિક ભારતીય આરોગ્યસંભાળ અનુભવ માટે વિશિષ્ટ સાધનો.",
            "feature1Title": "અહેવાલ વિશ્લેષણ",
            "feature1Desc": "AI તમારા લેબના પરિણામોને સરળ ભાષામાં સમજાવે છે.",
            "feature2Title": "AI હેલ્થ ચેટ",
            "feature2Desc": "તમારા આરોગ્ય ઇતિહાસ વિશે કંઈપણ પૂછો.",
            "feature3Title": "મેડિકેશન ટ્રેકર",
            "feature3Desc": "ક્યારેય કોઈ દવા ચૂકશો નહીં. સ્માર્ટ સમયપત્રક.",
            "feature4Title": "ઇન્સ્યોરન્સ નેવિગેટર",
            "feature4Desc": "PM-JAY યોજનાઓ શોધો જે તમારી સારવારને આવરી લે છે.",
            "feature5Title": "હેલ્થ ટાઇમલાઇન",
            "feature5Desc": "તમારી સંપૂર્ણ તબીબી મુસાફરી એક જ સમયરેખા પર.",
            "feature6Title": "ડૉક્ટર ડેશબોર્ડ",
            "feature6Desc": "ડૉક્ટરો દર્દીઓનું નિરીક્ષણ કરે છે અને જોખમ ધરાવતા દર્દીઓને ઓળખે છે."
        },
        "Dashboard": {
            "greeting": "નમસ્તે",
            "welcomeText": "આજે તમારા સ્વાસ્થ્ય સાથે શું થઈ રહ્યું છે તે અહીં છે.",
            "quickActions": "ઝડપી ક્રિયાઓ",
            "uploadReportBtn": "અહેવાલ અપલોડ કરો",
            "addMedicationBtn": "દવા ઉમેરો",
            "chatWithAIBtn": "AI સાથે ચેટ કરો",
            "recentReports": "તાજેતરના અહેવાલો",
            "noReports": "હજુ સુધી કોઈ રિપોર્ટ અપલોડ થયો નથી.",
            "uploadYourFirstReport": "શરૂ કરવા માટે તમારો પ્રથમ તબીબી રિપોર્ટ અપલોડ કરો."
        }
    }
}

for loc, content in locales.items():
    with open(f"messages/{loc}.json", "w", encoding="utf-8") as f:
        json.dump(content, f, ensure_ascii=False, indent=2)

print("Translation files generated successfully.")
