services:
  db:
    image: postgres:15
    container_name: careflow_db
    restart: always
    environment:
      POSTGRES_USER: careflow_user
      POSTGRES_PASSWORD: careflow_password
      POSTGRES_DB: careflow_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: careflow_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://careflow_user:careflow_password@db:5432/careflow_db
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: careflow_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: