"""Add provider profiles and user profile fields

Revision ID: 0b3de4eb89b5
Revises: c23440e8eb5d
Create Date: 2026-07-08 19:33:56.312864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3de4eb89b5'
down_revision: Union[str, None] = 'c23440e8eb5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nmc_registration_number', sa.String(length=50), nullable=True),
    sa.Column('medical_council', sa.String(length=100), nullable=True),
    sa.Column('qualification_degree', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_provider_profiles_nmc_registration_number'), 'provider_profiles', ['nmc_registration_number'], unique=True)
    op.add_column('medications', sa.Column('hospital_notes', sa.Text(), nullable=True))
    op.add_column('medications', sa.Column('previous_dosage', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('abha_id', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('state_residence', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('preferred_locale', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('blood_group', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_abha_id'), 'users', ['abha_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_abha_id'), table_name='users')
    op.drop_column('users', 'emergency_contact_phone')
    op.drop_column('users', 'emergency_contact_name')
    op.drop_column('users', 'blood_group')
    op.drop_column('users', 'preferred_locale')
    op.drop_column('users', 'state_residence')
    op.drop_column('users', 'abha_id')
    op.drop_column('medications', 'previous_dosage')
    op.drop_column('medications', 'hospital_notes')
    op.drop_index(op.f('ix_provider_profiles_nmc_registration_number'), table_name='provider_profiles')
    op.drop_table('provider_profiles')
    # ### end Alembic commands ###
