"""Add processing_progress to Report

Revision ID: 107164b79b12
Revises: dde3d9a91f9c
Create Date: 2026-07-09 01:54:33.594000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107164b79b12'
down_revision: Union[str, None] = 'dde3d9a91f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('processing_progress', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'processing_progress')
    # ### end Alembic commands ###
