"""Add image_url and metadata_json to chat_messages

Revision ID: 88903fea3d11
Revises: f426d0a87035
Create Date: 2026-07-10 16:47:12.732267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88903fea3d11'
down_revision: Union[str, None] = 'f426d0a87035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('chat_messages', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'metadata_json')
    op.drop_column('chat_messages', 'image_url')
    # ### end Alembic commands ###
