"""add insurance_queries table

Revision ID: a0357b939647
Revises: 
Create Date: 2026-06-29 15:48:15.816715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0357b939647'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_messages_session_id', table_name='chat_messages')
    op.drop_index('idx_chat_messages_timestamp', table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_timestamp'), 'chat_messages', ['timestamp'], unique=False)
    op.drop_index('idx_chat_sessions_user_id', table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.drop_index('idx_follow_ups_appointment_date', table_name='follow_ups')
    op.drop_index('idx_follow_ups_user_id', table_name='follow_ups')
    op.create_index(op.f('ix_follow_ups_appointment_date'), 'follow_ups', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_follow_ups_user_id'), 'follow_ups', ['user_id'], unique=False)
    op.drop_index('idx_timeline_event_date', table_name='health_timeline_events')
    op.drop_index('idx_timeline_user_id', table_name='health_timeline_events')
    op.create_index(op.f('ix_health_timeline_events_event_date'), 'health_timeline_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_health_timeline_events_user_id'), 'health_timeline_events', ['user_id'], unique=False)
    op.drop_index('idx_insurance_queries_user_id', table_name='insurance_queries')
    op.create_index(op.f('ix_insurance_queries_user_id'), 'insurance_queries', ['user_id'], unique=False)
    op.drop_index('idx_medication_logs_medication_id', table_name='medication_logs')
    op.drop_index('idx_medication_logs_scheduled_time', table_name='medication_logs')
    op.create_index(op.f('ix_medication_logs_medication_id'), 'medication_logs', ['medication_id'], unique=False)
    op.create_index(op.f('ix_medication_logs_scheduled_time'), 'medication_logs', ['scheduled_time'], unique=False)
    op.drop_index('idx_medications_is_active', table_name='medications')
    op.drop_index('idx_medications_user_id', table_name='medications')
    op.create_index(op.f('ix_medications_is_active'), 'medications', ['is_active'], unique=False)
    op.create_index(op.f('ix_medications_user_id'), 'medications', ['user_id'], unique=False)
    op.drop_constraint('provider_patients_provider_id_patient_id_key', 'provider_patients', type_='unique')
    op.create_unique_constraint('uq_provider_patient', 'provider_patients', ['provider_id', 'patient_id'])
    op.drop_index('idx_reports_uploaded_at', table_name='reports')
    op.drop_index('idx_reports_user_id', table_name='reports')
    op.create_index(op.f('ix_reports_uploaded_at'), 'reports', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_uploaded_at'), table_name='reports')
    op.create_index('idx_reports_user_id', 'reports', ['user_id'], unique=False)
    op.create_index('idx_reports_uploaded_at', 'reports', [sa.text('uploaded_at DESC')], unique=False)
    op.drop_constraint('uq_provider_patient', 'provider_patients', type_='unique')
    op.create_unique_constraint('provider_patients_provider_id_patient_id_key', 'provider_patients', ['provider_id', 'patient_id'])
    op.drop_index(op.f('ix_medications_user_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_is_active'), table_name='medications')
    op.create_index('idx_medications_user_id', 'medications', ['user_id'], unique=False)
    op.create_index('idx_medications_is_active', 'medications', ['is_active'], unique=False)
    op.drop_index(op.f('ix_medication_logs_scheduled_time'), table_name='medication_logs')
    op.drop_index(op.f('ix_medication_logs_medication_id'), table_name='medication_logs')
    op.create_index('idx_medication_logs_scheduled_time', 'medication_logs', [sa.text('scheduled_time DESC')], unique=False)
    op.create_index('idx_medication_logs_medication_id', 'medication_logs', ['medication_id'], unique=False)
    op.drop_index(op.f('ix_insurance_queries_user_id'), table_name='insurance_queries')
    op.create_index('idx_insurance_queries_user_id', 'insurance_queries', ['user_id'], unique=False)
    op.drop_index(op.f('ix_health_timeline_events_user_id'), table_name='health_timeline_events')
    op.drop_index(op.f('ix_health_timeline_events_event_date'), table_name='health_timeline_events')
    op.create_index('idx_timeline_user_id', 'health_timeline_events', ['user_id'], unique=False)
    op.create_index('idx_timeline_event_date', 'health_timeline_events', [sa.text('event_date DESC')], unique=False)
    op.drop_index(op.f('ix_follow_ups_user_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_appointment_date'), table_name='follow_ups')
    op.create_index('idx_follow_ups_user_id', 'follow_ups', ['user_id'], unique=False)
    op.create_index('idx_follow_ups_appointment_date', 'follow_ups', ['appointment_date'], unique=False)
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.create_index('idx_chat_sessions_user_id', 'chat_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_chat_messages_timestamp'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.create_index('idx_chat_messages_timestamp', 'chat_messages', [sa.text('timestamp DESC')], unique=False)
    op.create_index('idx_chat_messages_session_id', 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###
