"""Add status to medications

Revision ID: a8ff26a43b39
Revises: de04896059dd
Create Date: 2026-07-12 17:33:43.956456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ff26a43b39'
down_revision: Union[str, None] = 'de04896059dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medications', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'status')
    # ### end Alembic commands ###
