"""Add genuine provider fields

Revision ID: de04896059dd
Revises: 1fe0d8e4f15a
Create Date: 2026-07-12 16:44:29.001608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de04896059dd'
down_revision: Union[str, None] = '1fe0d8e4f15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('specialization', sa.String(length=100), nullable=True))
    op.add_column('provider_profiles', sa.Column('hospital_affiliation', sa.String(length=200), nullable=True))
    op.add_column('provider_profiles', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('provider_profiles', sa.Column('contact_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_profiles', 'contact_number')
    op.drop_column('provider_profiles', 'experience_years')
    op.drop_column('provider_profiles', 'hospital_affiliation')
    op.drop_column('provider_profiles', 'specialization')
    # ### end Alembic commands ###
