"""add analyzed_at to report

Revision ID: f426d0a87035
Revises: 6ab4f5cb9230
Create Date: 2026-07-09 23:07:10.209284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f426d0a87035'
down_revision: Union[str, None] = '6ab4f5cb9230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'analyzed_at')
    # ### end Alembic commands ###
